import type { InboxMessage } from "@/types/inbox";

export const mockInboxMessages: InboxMessage[] = [
  {
    id: "1",
    platform: "whatsapp",
    customerName: "John Mensah",
    phoneNumber: "+233 24 123 4567",
    customerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    lastMessage: "Hi, I want to order a custom agbada for my wedding",
    lastMessageTime: new Date("2025-01-30T10:30:00"),
    unreadCount: 2,
    status: "new",
    hasAttachment: false,
    messages: [
      {
        id: "m1",
        sender: "customer",
        content: "Hello! I saw your designs on Instagram",
        timestamp: new Date("2025-01-30T10:25:00"),
        type: "text",
      },
      {
        id: "m2",
        sender: "customer",
        content: "Hi, I want to order a custom agbada for my wedding",
        timestamp: new Date("2025-01-30T10:30:00"),
        type: "text",
      },
    ],
  },
  {
    id: "2",
    platform: "instagram",
    customerName: "Akosua Adjei",
    instagramHandle: "@akosua_styles",
    customerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Akosua",
    lastMessage: "Sent a photo",
    lastMessageTime: new Date("2025-01-30T09:15:00"),
    unreadCount: 0,
    status: "replied",
    hasAttachment: true,
    messages: [
      {
        id: "m3",
        sender: "customer",
        content: "I love this dress! Can you make something similar?",
        timestamp: new Date("2025-01-30T09:00:00"),
        type: "text",
      },
      {
        id: "m4",
        sender: "customer",
        content: "Here's the reference image",
        timestamp: new Date("2025-01-30T09:15:00"),
        type: "image",
        attachmentUrl: "https://placehold.co/400x600/png?text=Reference+Dress",
      },
      {
        id: "m5",
        sender: "business",
        content: "Beautiful! Yes, we can create that. When do you need it by?",
        timestamp: new Date("2025-01-30T09:20:00"),
        type: "text",
        deliveryStatus: "read",
      },
    ],
  },
  {
    id: "3",
    platform: "whatsapp",
    customerName: "Kwame Boateng",
    phoneNumber: "+233 20 987 6543",
    customerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kwame",
    lastMessage: "Thank you! The suit fits perfectly",
    lastMessageTime: new Date("2025-01-29T16:45:00"),
    unreadCount: 0,
    status: "resolved",
    hasAttachment: true,
    messages: [
      {
        id: "m6",
        sender: "customer",
        content: "I picked up my suit today",
        timestamp: new Date("2025-01-29T16:30:00"),
        type: "text",
      },
      {
        id: "m7",
        sender: "customer",
        content: "Thank you! The suit fits perfectly",
        timestamp: new Date("2025-01-29T16:45:00"),
        type: "text",
      },
      {
        id: "m8",
        sender: "customer",
        content: "Here's a photo!",
        timestamp: new Date("2025-01-29T16:46:00"),
        type: "image",
        attachmentUrl: "https://placehold.co/400x600/png?text=Customer+Photo",
      },
      {
        id: "m9",
        sender: "business",
        content: "You look amazing! Thank you for choosing us 🎉",
        timestamp: new Date("2025-01-29T17:00:00"),
        type: "text",
        deliveryStatus: "read",
      },
    ],
  },
  {
    id: "4",
    platform: "instagram",
    customerName: "Ama Sarpong",
    instagramHandle: "@ama_fashion",
    customerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ama",
    lastMessage: "What's your current turnaround time?",
    lastMessageTime: new Date("2025-01-29T14:20:00"),
    unreadCount: 1,
    status: "pending",
    hasAttachment: false,
    messages: [
      {
        id: "m10",
        sender: "customer",
        content: "Hi! Do you do kente styles?",
        timestamp: new Date("2025-01-29T14:00:00"),
        type: "text",
      },
      {
        id: "m11",
        sender: "business",
        content: "Yes! We specialize in modern kente designs. What are you looking for?",
        timestamp: new Date("2025-01-29T14:05:00"),
        type: "text",
        deliveryStatus: "read",
      },
      {
        id: "m12",
        sender: "customer",
        content: "A kente kaba and slit for a wedding",
        timestamp: new Date("2025-01-29T14:10:00"),
        type: "text",
      },
      {
        id: "m13",
        sender: "business",
        content: "Perfect! We have beautiful kente fabrics. When is the wedding?",
        timestamp: new Date("2025-01-29T14:12:00"),
        type: "text",
        deliveryStatus: "delivered",
      },
      {
        id: "m14",
        sender: "customer",
        content: "It's in 3 weeks",
        timestamp: new Date("2025-01-29T14:15:00"),
        type: "text",
      },
      {
        id: "m15",
        sender: "customer",
        content: "What's your current turnaround time?",
        timestamp: new Date("2025-01-29T14:20:00"),
        type: "text",
      },
    ],
  },
  {
    id: "5",
    platform: "whatsapp",
    customerName: "Yaw Osei",
    phoneNumber: "+233 55 444 3333",
    customerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yaw",
    lastMessage: "Can I get my measurements adjusted?",
    lastMessageTime: new Date("2025-01-28T11:30:00"),
    unreadCount: 0,
    status: "replied",
    hasAttachment: false,
    messages: [
      {
        id: "m16",
        sender: "customer",
        content: "Hello, I ordered a kaftan last month",
        timestamp: new Date("2025-01-28T11:00:00"),
        type: "text",
      },
      {
        id: "m17",
        sender: "customer",
        content: "Can I get my measurements adjusted?",
        timestamp: new Date("2025-01-28T11:30:00"),
        type: "text",
      },
      {
        id: "m18",
        sender: "business",
        content: "Of course! Please come by the shop anytime this week",
        timestamp: new Date("2025-01-28T11:45:00"),
        type: "text",
        deliveryStatus: "read",
      },
    ],
  },
];
