name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: |
          bun run build:api
          bun run build:admin

      - name: Setup Supabase CLI (for type drift check)
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' }}
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase types drift check
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase login --token "$SUPABASE_ACCESS_TOKEN"
          bun run db:types
          git diff --exit-code -- packages/supabase/src/types/database.ts

      - name: Verify RLS (optional)
        if: ${{ env.NEXT_PUBLIC_SUPABASE_URL != '' && env.NEXT_PUBLIC_SUPABASE_ANON_KEY != '' && env.RLS_VERIFY_TOKEN != '' }}
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          RLS_VERIFY_TOKEN: ${{ secrets.RLS_VERIFY_TOKEN }}
        run: bun run verify:rls
